### ISSUE TITLE
Setup monitoring of harbor through prometheus

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#100]
We need to be automatically notified when something goes wrong with harbor. This requires a few things to be done:

- [x] Discover which metrics are exposed through harbor
- [x] Write prometheus rules to alert on faulty behavior
- [x] Setup forwarding to specific channel shared with CS to receive alerts
- [ ] Link operational documentation #98 to specific alerts

**Comment by MarcelMue** [comment]
- [ ] Grafana dashboard for an overview of harbor (nice to have)

**Comment by cagiti** [comment]
I can see that prometheus and grafana are deployed within the `ginger` & `gauss` clusters, can we leverage these deployments or should separate instances of each be deployed?

**Comment by cagiti** [comment]
For info:
- https://goharbor.io/docs/2.2.0/administration/metrics/
- https://grafana.com/grafana/dashboards/14075-harbor/

**Comment by MarcelMue** [comment]
> In addition to these metrics Prometheus should have access to the states of the pods inside the cluster. With this in mind what metrics are the most relevant for triggering alerts on faulty behaviours?

I think understanding what would indicate a broken harbor is most important here. E.g. `storage action seconds` seems quite important but no clue what a normal / unusual value would be.
