### ISSUE TITLE
[SPIKE] What will the default configuration of using  harbor for production look like?

### ISSUE THREAD

**Issue by ladeoshodi** [giantswarm/harbor-app#56]
Notes:
- Create an ADR with pros and cons

Discovery topics:
1. **Discovery topic: What would configuration look like if harbor-operator is used?**
- What are the permissions to workload cluster

2. Discovery topic: What are community guidelines for production readiness?
- Community guidelines

**Comment by MarcelMue** [comment]
This is essentially the containerd config @DeeAjayi is working on.
