### ISSUE TITLE
[SPIKE] What is the high-level architecture for implementing harbor as an app for Giant Swarm?

### ISSUE THREAD

**Issue by ladeoshodi** [giantswarm/harbor-app#58]
Options:
a. Harbor as a management cluster local cache only.
b. Harbor replicates from a cloud registry.
c. Harbor replicates from other Harbor instances.

**Comment by MarcelMue** [comment]
We start with this issue, if there is a dependency to storage which comes up, then we re-discuss and switch focus to storage exploration.
