### ISSUE TITLE
Have harbor operator running on gauss

### ISSUE THREAD

**Issue by ladeoshodi** [giantswarm/harbor-app#64]
Goal:
- Can the webUI be accessed?
- Can you login to the webUI?

Tasks
 [✅] The TLS configuration for Minio operator is done manually - done
 [] Automatic TLS configuration for Minio operator #67

**Comment by raha-farokhi** [comment]
As Minio operator is one optional feature for Harbor Cluster. Instead of using Minio we tried other options like Filesystm and AWS S3. Which both of them work fine.

Tasks:

- [ ] Harbor Cluster up and running using File System

- [ ] Harbor Cluster up and running using S3
