### ISSUE TITLE
Figure out if minio is needed and test on eks with S3

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#69]
- [x] Check if minio is needed to run on AWS
- [x] Check why minio is needed at all

**Comment by raha-farokhi** [comment]
- [ ] Minio is not needed to run Harbor cluster on EKS. it is optional You can choose among Filesystem, S3, Minio for AWS or even gcs, swift and azure for other cloud providers.
- [ ] MinIO is a Kubernetes-native high performance object store with an S3-compatible API. Minio is an object storage server that implements the same public API as Amazon S3. This means that applications that can be configured to talk to Amazon S3 can also be configured to talk to Minio.
