### ISSUE TITLE
Test caching mechanisms in Harbor

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#76]
- Can we reconfigure some pods to pull from harbor which acts as a cache?
- Can we cache OCI artifacts (such as helm charts)?
- How is caching configured on harbor? Is it possible to automatically apply configuration to many harbor instances?

**Comment by William-Young-97** [comment]
- [ ] Can we reconfigure some pods to pull from harbor which acts as a cache?
Yes, tested for both public and private harbor cache projects

- [ ] Can we cache OCI artifacts (such as helm charts)?
Yes, pulled from Azure public ACR

- [ ]  How is caching configured on harbor? Is it possible to automatically apply configuration to many harbor instances?
TBD
