### ISSUE TITLE
Debug harbor and harbor-operator stability

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#77]
This is a long term issue where we collect issues we had concerning the stability of both harbor and harbor-operator and document how we were able to fix them.

**Comment by William-Young-97** [comment]
- Issue seems to be related to a throttling on the Kubernetes side.
- We have circumvented this for now by extending the period seconds and failure threshold of the liveness and ready probes, in the harbor-operator deployment.
- Will continue to monitor the situation.

**Comment by William-Young-97** [comment]
UPDATE:

- Not long into trying to use harbor ui the pod started to crash off again.
- Continuing to troubleshoot

**Comment by MarcelMue** [comment]
We have some ops recipes now - we should iterate on those.
