### ISSUE TITLE
Clean up harbor-operator repository and automate deployment more

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#78]
- We should check if we can restructure the app repository to move CRDs into the CRD folder https://github.com/giantswarm/harbor-operator-app/tree/master/helm/harbor-operator
- We should check how many manual actions need to currently take place after we create the app CR and if we can automate them more

**Comment by MarcelMue** [comment]
Goal: The upstream chart should be in the `charts` subdirectory to enable us to get a fresh upstream release without merge conflicts

**Comment by MarcelMue** [comment]
Use the kyverno-app repo as reference:
https://github.com/giantswarm/kyverno-app/tree/main/helm/kyverno

**Comment by cagiti** [comment]
> https://github.com/giantswarm/harbor-app/issues/78#issuecomment-1293144541

Looks like this is done

**Comment by cagiti** [comment]
https://github.com/giantswarm/harbor-operator-app/pull/77
