### ISSUE TITLE
Use fork for goharbor-client in GS org

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#94]
We should use an internal fork instead: https://github.com/giantswarm/goharbor-client

Additionally we should update vulnerable dependencies in the fork. We can later push them to the original repository.

**Comment by cagiti** [comment]
@MarcelMue: what is the plan for the release of this forked repo? Do you want circleci to perform releases, use the github actions or copy the tags over from upstream?

**Comment by MarcelMue** [comment]
> @MarcelMue: what is the plan for the release of this forked repo? Do you want circleci to perform releases, use the github actions or copy the tags over from upstream?

I would personally use latest of the fork - golang should be ok to do that IIRC. Otherwise I would simply say we create a 1.0.0 tag and don't align with the upstream versioning.

Generally use your best judgement.

**Comment by cagiti** [comment]
https://github.com/giantswarm/harbor-config-operator/pull/21
