### ISSUE TITLE
Create upstream issues for open CVEs

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/harbor-app#95]
Our current implementation of `harbor-config-operator` contains a lot of CVEs coming from upstream. We should create issues in the relevant upstream repositories to update those dependencies.

Upstream repos:
- harbor
- harbor-operator

https://github.com/giantswarm/harbor-config-operator/blob/5d68753be09e142b6e37d641c9da26a05b1cd4c0/.nancy-ignore

**Comment by cagiti** [comment]
https://github.com/goharbor/harbor-operator/pull/985

**Comment by William-Young-97** [comment]
sonatype-2019-0890 - https://github.com/goharbor/harbor/pull/17899
